### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by hut** [project-talk-to-me/website#54]

**Comment by spirozh** [comment]
following the instructions in https://blog.benoitblanchon.fr/github-action-run-ssh-commands/ to set up the github action

**Comment by spirozh** [comment]
added workflow definition files to .github/workflows/
 * `test.yml` : runs the go test suite whenever a pull-request is opened, reopened, or synchronized
* `deploy.yml`: deploys to talk-to-me.help when there is a push to the `live` branch
